/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

enum ExocoreQueryStatus {
  ExocoreQueryStatus_Success = 0,
  ExocoreQueryStatus_Error,
};
typedef uint8_t ExocoreQueryStatus;

enum ExocoreStatus {
  ExocoreStatus_Success = 0,
};
typedef uint8_t ExocoreStatus;

typedef struct ExocoreContext ExocoreContext;

typedef struct ExocoreExocoreContext {
  ExocoreStatus status;
  ExocoreContext *context;
} ExocoreExocoreContext;

typedef struct ExocoreQueryHandle {
  ExocoreQueryStatus status;
  uint64_t query_id;
} ExocoreQueryHandle;

void exocore_context_free(ExocoreContext *ctx);

ExocoreExocoreContext exocore_context_new(void);

ExocoreQueryHandle exocore_query(ExocoreContext *ctx,
                                 const char *query,
                                 void (*on_ready)(ExocoreQueryStatus status, const char*));

void exocore_query_cancel(ExocoreContext *ctx, ExocoreQueryHandle handle);

ExocoreQueryHandle exocore_watched_query(ExocoreContext *ctx,
                                         const char *query,
                                         void (*on_change)(ExocoreQueryStatus status, const char*));
