[package]
name = "exocore-index"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]

[dependencies]
exocore-data = { path = "../data" }
exocore-common = { path = "../common" }
log = "0.4"

