[package]
name = "exocore-index"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[dependencies]
exocore-data = { path = "../data" }
exocore-transport = { path = "../transport" }
exocore-common = { path = "../common" }
log = "0.4"

