[package]
name = "exocore-index"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[dependencies]
exocore-data = { path = "../data" }
exocore-transport = { path = "../transport" }
exocore-common = { path = "../common" }
failure = "0.1"
futures = "0.1"
itertools = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.8"
maplit = "1"
tokio = { version = "0.1", features = ["io"] }
log = "0.4"
tantivy = "0.10"

[dev-dependencies]
tempdir = "0.3"
exocore-data = { path = "../data", features = ["tests_utils"] }
