[package]
name = "exocore-client-wasm"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
exocore-common = { path = "../../common" }
exocore-index = { path = "../../index" }
tokio = { version = "0.1", features = ["io"], default-features = false }
failure = "0.1"
wasm-bindgen = "0.2"
stdweb = "0.4"
