
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - script: |
      git submodule sync --recursive
      git submodule update --init --recursive
    displayName: 'Sync submodules'

  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
      rustc --version && cargo --version
      sudo apt update && sudo apt install -y capnproto libssl-dev pkg-config cmake zlib1g-dev
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    displayName: 'Install dependencies'
    
  - script: |
      export PATH=$PATH:$HOME/.cargo/bin
      cargo test --all --verbose -- --test-threads=1
    displayName: 'Test all'

  - script: |
      export PATH=$PATH:$HOME/.cargo/bin
      cargo tarpaulin --exclude-files=3rd --exclude-files="*_capnp.rs" --all --out Xml -v
    displayName: 'Code coverage'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: $(System.DefaultWorkingDirectory)/cobertura.xml
