
trigger:
- master


jobs:
  - job: Tests
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - checkout: self
        submodules: true

      - script: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          export PATH=$PATH:$HOME/.cargo/bin:/usr/local/cargo/bin
          rustc --version && cargo --version
          rustup component add rustfmt
          rustup component add clippy
        displayName: 'Install dependencies'

      - script: |
          set -e
          export PATH=$PATH:$HOME/.cargo/bin:/usr/local/cargo/bin

          cargo fmt --all -- --check
          cargo check --all
          cargo clean -p exocore-common
          cargo clippy --all -- -D clippy::all

          cargo test --all --verbose
        displayName: 'Test all'
#
# Disabled until Tarpaulin fixes their bugs...
# https://github.com/xd009642/tarpaulin/issues/190#issuecomment-491040656
#
#  - job: Coverage
#    pool:
#      vmImage: 'Ubuntu-16.04'
#
#    variables:
#      - group: master_builds
#
#    steps:
#      - checkout: self
#        submodules: true
#
#      - script: |
#          set -e
#          docker --version
#          ./utils/coverage.sh Xml no
#          bash <(curl -s https://codecov.io/bash)
#        displayName: 'Code coverage'

