
trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - script: |
      git submodule sync --recursive
      git submodule update --init --recursive
    displayName: 'Sync submodules'

  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
      apt update && apt install -y capnproto
      rustc --version && cargo --version
    displayName: 'Install dependencies'
    
  - script: |
      export PATH=$PATH:$HOME/.cargo/bin
      cargo test --all --verbose -- --test-threads=1
    displayName: 'Test all'