
trigger:
- master


jobs:
  - job: Tests
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - checkout: self
        submodules: true

      - script: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          export PATH=$PATH:$HOME/.cargo/bin:/usr/local/cargo/bin
          rustc --version && cargo --version
          rustup component add rustfmt
          rustup component add clippy
        displayName: 'Install dependencies'

      - script: |
          set -e
          export PATH=$PATH:$HOME/.cargo/bin:/usr/local/cargo/bin

          cargo fmt --all -- --check
          cargo check --all
          cargo clean -p exocore-common
          cargo clippy --all -- -D clippy::all

          cargo test --all --all-features
        displayName: 'Test all'

  - job: Coverage
    pool:
      vmImage: 'Ubuntu-16.04'

    variables:
      - group: master_builds

    steps:
      - checkout: self
        submodules: true

      - script: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
          export PATH=$PATH:$HOME/.cargo/bin:/usr/local/cargo/bin
          rustc --version && cargo --version
          rustup toolchain install nightly
        displayName: 'Install dependencies'

      - script: |
          set -e
          curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
          export PATH=$PATH:`pwd`
          ./utils/coverage.sh codecov_io
          bash <(curl -s https://codecov.io/bash)
        displayName: 'Code coverage'

