# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - script: |
      git submodule sync --recursive
      git submodule update --init --recursive
    displayName: 'Sync submodules'
  - script: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
    displayName: 'Install rustc'
  - script: |
      export PATH=$PATH:$HOME/.cargo/bin
      cargo build --verbose
    displayName: 'Build docs.rs'
  - script: |
      export PATH=$PATH:$HOME/.cargo/bin
      cargo test --verbose -- --test-threads=1
    displayName: 'Test docs.rs'