[package]
name = "exocore"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]

[dependencies]
exocore-server = { path = "./server" }
exocore-index = { path = "./index" }
exocore-data = { path = "./data" }
exocore-common = { path = "./common" }

[workspace]
members = [
  "server",
  "index",
  "data",
  "common",
]

#[patch.crates-io]
#extindex = { path = "./3rd/extindex" }
#capnp = { path = "./3rd/capnproto-rust/capnp" }
#extsort = { path = "./3rd/extsort" }
