[package]
name = "exocore"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]


[dependencies]
exocore-server = { path = "./server" }
exocore-index = { path = "./index" }
exocore-data = { path = "./data" }
exocore-common = { path = "./common" }
extsort = { path = "./3rd/extsort" }
extindex = { path = "./3rd/extindex" }


[workspace]
members = [
  "server",
  "index",
  "data",
  "common",
  "3rd/extsort"
]

[patch.crates-io]
extsort = { path = "./3rd/extsort" }
extindex = { path = "./3rd/extindex" }
