
[workspace]
members = [
  "cli",
  "index",
  "data",
  "common",
  "schema",
  "transport",
  "clients/wasm",
  "clients/android",
  "clients/ios",
]

[patch.crates-io]
tokio = { git = "https://github.com/appaquet/tokio", path = "./tokio", branch = "queue-reintrant-deadlock" }