[package]
name = "exocore"
description = "Distributed applications framework"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "web", "framework", "ios", "android", "webassembly", "storage", "database"]
categories = ["Database implementations", "Command-line interface", "WebAssembly", "Web programming"]
repository = "https://github.com/appaquet/exocore"
license = "MIT"

[dependencies]
exocore-common = { path = "./common" }
exocore-transport = { path = "./transport" }
exocore-schema = { path = "./schema" }
exocore-index = { path = "./index" }
exocore-data = { path = "./data" }

[dev-dependencies]
exocore-common = { path = "./common", features = ["tests_utils"] }

[workspace]
members = [
  "exo",
  "index",
  "data",
  "common",
  "schema",
  "transport",
  "clients/wasm",
  "clients/android",
  "clients/ios",
]

