[package]
name = "exocore"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]


[dependencies]
exocore-server = { path = "./server" }
exocore-index = { path = "./index" }
exocore-data = { path = "./data" }
exocore-common = { path = "./common" }

[workspace]
members = [
  "server",
  "index",
  "data",
  "common",
]
