[package]
name = "exocore"
description = "Distributed applications framework"
version = "0.1.3"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "Apache-2.0"

[features]
default = [
  "core-runtime",
  "core-logger",
  "transport-p2p",
  "transport-http-server",
  "store-local",
  "chain-engine",
  "chain-directory-chain",
  "chain-memory-pending",
]
tests-utils = ["exocore-core/tests-utils", "exocore-transport/tests-utils", "exocore-store/tests-utils"]
logger = ["core-logger"]

client = ["core-runtime", "transport-p2p"]
web = ["transport-p2p-web"]

core-runtime = ["exocore-core/runtime"]
core-logger = ["exocore-core/logger"]
transport-p2p = ["exocore-transport/p2p-full"]
transport-p2p-web = ["exocore-transport/p2p-web"]
transport-http-server = ["exocore-transport/http-server"]
store-local = ["exocore-store/local"]
chain-engine = ["exocore-chain/engine"]
chain-directory-chain = ["exocore-chain/directory-chain"]
chain-memory-pending = ["exocore-chain/memory-pending"]
discovery-server = ["exocore-discovery/server"]

[dependencies]
exocore-core = { version = "0.1.3", path = "./core", default-features = false }
exocore-transport = { version = "0.1.3", path = "./transport", default-features = false }
exocore-store = { version = "0.1.3", path = "./store", default-features = false }
exocore-chain = { version = "0.1.3", path = "./chain", default-features = false }
exocore-discovery = { version = "0.1.3", path = "./discovery", default-features = false }

[dev-dependencies]
exocore-core = { version = "0.1.3", path = "./core", features = ["tests-utils"] }

[workspace]
members = [
  "core",
  "transport",
  "store",
  "chain",
  "apps/runtime",
  "apps/sdk",
  "discovery",
  "exo",
  "clients/web",
  "clients/android",
  "clients/c",
]
exclude = [
    "3rd"
]

[profile.release]
lto = "thin"
codegen-units = 1