[package]
name = "exocore"
description = "Distributed applications framework"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "Apache-2.0"

[features]
default = ["core-runtime", "core-logger", "transport-p2p", "store-local", "chain-engine", "chain-directory-chain", "chain-memory-pending"]
tests-utils = ["exocore-core/tests-utils", "exocore-transport/tests-utils", "exocore-store/tests-utils"]
logger = ["core-logger"]

client = ["core-runtime", "transport-p2p"]
web = ["transport-p2p-web"]

core-runtime = ["exocore-core/runtime"]
core-logger = ["exocore-core/logger"]
transport-p2p = ["exocore-transport/p2p-full"]
transport-p2p-web = ["exocore-transport/p2p-web"]
store-local = ["exocore-store/local"]
chain-engine = ["exocore-chain/engine"]
chain-directory-chain = ["exocore-chain/directory-chain"]
chain-memory-pending = ["exocore-chain/memory-pending"]

[dependencies]
exocore-core = { version = "0.1.0", path = "./core", default-features = false }
exocore-transport = { version = "0.1.0", path = "./transport", default-features = false }
exocore-store = { version = "0.1.0", path = "./store", default-features = false }
exocore-chain = { version = "0.1.0", path = "./chain", default-features = false }

[dev-dependencies]
exocore-core = { version = "0.1.0", path = "./core", features = ["tests-utils"] }

[workspace]
members = [
  "exo",
  "store",
  "chain",
  "core",
  "transport",
  "clients/web",
  "clients/android",
  "clients/ios"
]
exclude = [
    "3rd"
]

[profile.release]
lto = "thin"
codegen-units = 1