
[workspace]
members = [
  "cli",
  "index",
  "data",
  "common",
  "transport",
  "clients/wasm",
  "clients/android",
]
default-members = [
  "cli",
  "index",
  "data",
  "common",
  "transport",
]
