[package]
name = "exocore"
description = "Distributed applications framework"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "MIT"

[dependencies]
exocore-core = { version = "0.1.0", path = "./core" }
exocore-transport = { version = "0.1.0", path = "./transport" }
exocore-index = { version = "0.1.0", path = "./index" }
exocore-data = { version = "0.1.0", path = "./data" }

[dev-dependencies]
exocore-core = { version = "0.1.0", path = "./core", features = ["tests_utils"] }

[workspace]
members = [
  "exo",
  "index",
  "data",
  "core",
  "transport",
  "clients/web",
  "clients/android",
  "clients/ios"
]
exclude = [
    "3rd"
]

[profile.release]
codegen-units = 1
lto="fat"
