[target.armv7-unknown-linux-gnueabihf]
pre-build = ["apt-get update && apt-get install --assume-yes protobuf-compiler clang"]

[target.x86_64-unknown-linux-gnu]
pre-build = ["apt-get update && apt-get install --assume-yes protobuf-compiler clang"]