[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
name = "exocore-client-c"
version = "0.1.3"

[lib]
crate-type = ["staticlib", "cdylib"]
name = "exocore"

[dependencies]
exocore-core = {version = "0.1.3", path = "../../core", features = ["runtime", "logger"]}
exocore-discovery = {version = "0.1.3", path = "../../discovery", default-features = false}
exocore-protos = {version = "0.1.3", path = "../../protos"}
exocore-store = {version = "0.1.3", path = "../../store", default-features = false, features = ["remote"]}
exocore-transport = {version = "0.1.3", path = "../../transport", features = ["p2p-full"]}
futures = "0.3"
libc = "0.2"
log = "0.4"
log4rs = "1.0"
serde_json = "1.0"
