[package]
name = "exocore-client-android"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
exocore-core = { path = "../../core", features = ["runtime", "logger"] }
exocore-transport = { path = "../../transport", features = ["p2p-full"] }
exocore-store = { path = "../../store" }
thiserror = "1.0"
anyhow = "1.0"
