[package]
name = "exocore-client-web"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
exocore-core = { path = "../../core", default-features = false  }
exocore-index = { path = "../../index", default-features = false }
exocore-transport = { path = "../../transport", default-features = false, features = ["libp2p-web"]  }
thiserror = "1.0"
anyhow = "1.0"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] } # serde for serialization from JsValue
wasm-bindgen-futures = "0.4"
console_error_panic_hook = "0.1"
js-sys = "0.3"
log = "0.4"
wasm-logger = "0.2"
futures = "0.3"
prost = "0.6"

# Temporary until https://github.com/rustwasm/wasm-pack/issues/886 is fixed
[package.metadata.wasm-pack.profile.release]
wasm-opt = ["--enable-mutable-globals"]