[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Distributed applications framework"
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-apps-sdk"
repository = "https://github.com/appaquet/exocore"
version = "0.1.14"

[dependencies]
anyhow = "1.0"
exocore-apps-macros = {version = "0.1.14", path = "../macros"}
exocore-protos = {version = "0.1.14", path = "../../protos"}
exocore-store = {version = "0.1.14", path = "../../store", default-features = false}
futures = "0.3"
lazy_static = "1.4"
log = "0.4"
quote = "1.0"
thiserror = "1.0"
chrono = "0.4"

[dev-dependencies]
tokio = {version = "1.12", features = ["macros"], default-features = false}
