[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Protobuf and cap'n protos of Exocore (Distributed applications framework)"
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-protos"
repository = "https://github.com/appaquet/exocore"
version = "0.1.3"

[dependencies]
anyhow = "1.0"
base64 = "0.13"
capnp = {version = "0.14", features = ["sync_reader"]}
chrono = "0.4"
prost = "0.7"
prost-types = "0.7"
protobuf = "2"
serde = "1.0"
serde_derive = "1.0"
thiserror = "1.0"

[build-dependencies]
capnpc = "0.14"
prost-build = "0.7"
