[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Protobuf and cap'n protos of Exocore (Distributed applications framework)"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-protos"
repository = "https://github.com/appaquet/exocore"
version = "0.1.23"

[dependencies]
anyhow = "1.0.62"
base64 = "0.13.0"
capnp = { version = "0.14.8", features = ["sync_reader"] }
chrono = "0.4.22"
prost = "0.11.0"
prost-types = "0.11.1"
protobuf = "3.1.0"
serde = "1.0.143"
serde_derive = "1.0.142"
serde_json = "1.0.85"
thiserror = "1.0.32"

[build-dependencies]
capnpc = "0.14.9"
prost-build = "0.11.1"
