[package]
name = "exocore-core"
description = "Core of Exocore (Distributed applications framework)"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "Apache-2.0"

[features]
tests-utils = ["runtime", "logger"]
runtime = [
    "tokio/io-driver",
    "tokio/io-util",
    "tokio/io-std",
    "tokio/tcp",
    "tokio/rt-core",
    "tokio/rt-util",
    "tokio/rt-threaded",
    "tokio/stream",
    "tokio/sync",
    "tokio/time",
    "tokio/macros"
]
logger = ["log4rs"]

[dependencies]
log = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
multihash = "0.11"
bs58 = "0.3"
capnp = { version = "0.13", git = "https://github.com/appaquet/capnproto-rust.git", branch = "atomic-read-limiter" }
byteorder = "1.3"
thiserror = "1.0"
anyhow = "1.0"
libp2p = { version = "0.28", features = ["noise"], default-features = false }
chrono = "0.4"
wasm-timer = "0.2"
futures = { version = "0.3", features = ["async-await", "compat"] }
tokio = { version = "0.2", features = ["rt-core", "blocking"], default-features = false }
protobuf = "2"
prost = "0.6"
prost-types = "0.6"
bytes = "0.5"
uuid = { version = "0.8", features = ["v4", "wasm-bindgen"] }
petname = "1.0"
rand = "0.7"
url = "2.1"

# console_logger
log4rs = { version = "0.13", optional = true }

[target."cfg(all(target_arch = \"wasm32\", target_os = \"unknown\"))".dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

[build-dependencies]
capnpc = { version = "0.13", git = "https://github.com/appaquet/capnproto-rust.git", branch = "atomic-read-limiter" }
prost-build = "0.6"

[dev-dependencies]
tempfile = "3.1"
log4rs = "0.13"
criterion_bencher_compat = "0.3"

[[bench]]
name = "capnp_frame"
harness = false
