[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "Distributed applications framework"
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exocore-apps-host"
repository = "https://github.com/appaquet/exocore"
version = "0.1.6"

[features]
default = []

[dependencies]
anyhow = "1.0"
exocore-core = {version = "0.1.6", path = "../../core"}
exocore-protos = {version = "0.1.6", path = "../../protos"}
exocore-store = {version = "0.1.6", path = "../../store"}
futures = "0.3"
log = "0.4"
reqwest = {version = "0.11", default-features = false, features = ["rustls-tls"]}
thiserror = "1.0"

[target."cfg(any( all(target_arch = \"x86_64\", any(target_os = \"linux\", target_os = \"darwin\", target_os = \"windows\")), all(target_arch = \"aarch64\", target_os = \"linux\") ))".dependencies]
wasmtime = "0.27.0"

[dev-dependencies]
exocore-core = {version = "0.1.6", path = "../../core", features = ["tests-utils"]}
