[package]
name = "exocore-server"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[dependencies]
exocore-data = { path = "../data" }
exocore-index = { path = "../index" }
exocore-common = { path = "../common" }
exocore-transport = { path = "../transport" }
log = "0.4"
structopt = "0.2"
log4rs = "0.8"
failure = { version ="0.1.5", features = ["backtrace"] }
tokio = "0.1"
