[package]
name = "exocore-transport"
description = "Transport layer of Exocore (Distributed applications framework)"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "MIT"

[features]
default = ["websocket_transport", "libp2p_transport"]
tests_utils = ["exocore-core/tests_utils"]
websocket_transport = ["websocket"]
libp2p_transport = ["libp2p"]

[dependencies]
exocore-core = { path = "../core" }
log = "0.4"
failure = "0.1"
futures = { version = "0.3", features = ["compat"] }
futures01 = { package = "futures", version = "0.1" }
pin-project = "0.4"

# Websocket transport
websocket = { version = "0.24", optional = true, default-features = false, features = ["async"] }

# libp2p transport
libp2p = { version = "0.13", optional = true, default-features = false, features = ["secp256k1"] }

[dev-dependencies]
exocore-core = { path = "../core", features = ["tests_utils"] }
