[package]
name = "exocore-transport"
description = "Transport layer of Exocore (Distributed applications framework)"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "web", "framework", "ios", "android", "webassembly", "storage", "database"]
categories = ["Database implementations", "Command-line interface", "WebAssembly", "Web programming"]
repository = "https://github.com/appaquet/exocore"
license = "MIT"

[features]
tests_utils = ["exocore-common/tests_utils"]
websocket_transport = ["websocket"]
libp2p_transport = ["libp2p"]

[dependencies]
exocore-common = { path = "../common" }
log = "0.4"
failure = "0.1"
futures = { version = "0.3", features = ["compat"] }
futures01 = { package = "futures", version = "0.1" }
pin-project = "0.4"

# Websocket transport
websocket = { version = "0.24", optional = true, default-features = false, features = ["async"] }

# libp2p transport
libp2p = { version = "0.13", features = ["secp256k1"], default-features = false, optional = true }

[dev-dependencies]
exocore-common = { path = "../common", features = ["tests_utils"] }
