[package]
name = "exocore-transport"
description = "Transport layer of Exocore (Distributed applications framework)"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "Apache-2.0"

[features]
default = ["libp2p-full"]
tests-utils = ["exocore-core/tests-utils"]
libp2p-web = ["libp2p-base", "libp2p/wasm-ext", "libp2p-wasm-ext"] 
libp2p-full = ["libp2p-base", "libp2p/tcp-tokio"]
libp2p-base = ["libp2p"]

[dependencies]
exocore-core = { path = "../core" }
log = "0.4"
thiserror = "1.0"
anyhow = "1.0"
futures = { version = "0.3", features = ["compat"] }
pin-project = "0.4"
byteorder = "1.3"
libp2p = { version = "0.23.0", optional = true, default-features = false, features = [ "dns", "mplex", "secio", "websocket", "yamux" ] }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
libp2p-wasm-ext = { version = "0.20", features = ["websocket"], optional = true }
wasm-bindgen = "0.2"

[dev-dependencies]
exocore-core = { path = "../core", features = ["tests-utils"] }
