[package]
name = "exocore-transport"
description = "Transport layer of Exocore (Distributed applications framework)"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "Apache-2.0"

[features]
default = ["p2p-full", "http-server"]
tests-utils = ["exocore-core/tests-utils"]
p2p-web = ["p2p-base", "libp2p/wasm-ext-websocket"] 
p2p-full = ["p2p-base", "libp2p/tcp-tokio"]
p2p-base = ["libp2p"]
http-server = ["hyper", "url"]

[dependencies]
exocore-core = { path = "../core" }
log = "0.4"
thiserror = "1.0"
anyhow = "1.0"
futures = { version = "0.3", features = ["compat"] }
pin-project = "1.0"
byteorder = "1.3"
libp2p = { version = "0.28", optional = true, default-features = false, features = [ "dns", "mplex", "noise", "websocket", "yamux" ] }
hyper = { version = "0.13", optional = true }
url = { version = "2.1", optional = true }

[target.'cfg(all(target_arch = "wasm32", target_os = "unknown"))'.dependencies]
wasm-bindgen = "0.2"

[dev-dependencies]
exocore-core = { path = "../core", features = ["tests-utils"] }
tokio = "0.2"