[package]
name = "exocore-transport"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[features]
tests_utils = []

[dependencies]
exocore-common = { path = "../common" }
futures = "0.1"
log = "0.4"
failure = { version ="0.1.5", features = ["backtrace"] }
libp2p = "0.7.0"
tokio-io = "0.1"
tokio-timer = "0.2"
tokio-executor = "0.1"

[dev-dependencies]
tokio = { version = "0.1" }
exocore-common = { path = "../common", features = ["tests_utils"] }
