[package]
name = "exocore-transport"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[features]
tests_utils = []

[dependencies]
exocore-common = { path = "../common" }
futures = "0.1"
log = "0.4"
failure = { version ="0.1.5", features = ["backtrace"] }
tokio = "0.1"
libp2p = "0.7.0"

[dev-dependencies]
exocore-common = { path = "../common", features = ["tests_utils"] }

