[package]
name = "exo"
description = "CLI for Exocore (Distributed applications framework)"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "web", "framework", "ios", "android", "webassembly", "storage", "database"]
categories = ["Database implementations", "Command-line interface", "WebAssembly", "Web programming"]
repository = "https://github.com/appaquet/exocore"
license = "MIT"

[dependencies]
exocore-common = { path = "../common", features = ["runtime"] }
exocore-schema = { path = "../schema" }
exocore-data = { path = "../data", features = ["engine", "directory_chain", "memory_pending"] }
exocore-index = { path = "../index", features = ["local_store"] }
exocore-transport = { path = "../transport", features = ["websocket_transport", "libp2p_transport"] }
log = "0.4"
structopt = "0.3"
log4rs = "0.9"
failure = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
futures = "0.3"
