[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "CLI for Exocore (Distributed applications framework)"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exo"
repository = "https://github.com/appaquet/exocore"
version = "0.1.24"

[dependencies]
anyhow = "1.0.66"
bytes = "1.2.1"
clap = { version = "4.0.22", features = ["derive", "env"] }
console = "0.15.2"
dialoguer = "0.10.2"
dirs-next = "2.0.0"
exocore-apps-host = {version = "0.1.24", path = "../apps/host"}
exocore-chain = {version = "0.1.24", path = "../chain"}
exocore-core = {version = "0.1.24", path = "../core", features = ["runtime", "logger"]}
exocore-discovery = {version = "0.1.24", path = "../discovery", features = ["server"]}
exocore-protos = {version = "0.1.24", path = "../protos"}
exocore-store = {version = "0.1.24", path = "../store"}
exocore-transport = {version = "0.1.24", path = "../transport", features = ["http-server"]}
futures = "0.3.25"
indicatif = "0.17.2"
log = "0.4.17"
log4rs = "1.2.0"
rand = "0.8"
reqwest = { version = "0.11.12", default-features = false, features = ["rustls-tls"] }
serde = "1.0.147"
serde_derive = "1.0.147"
serde_json = "1.0.87"
tempfile = "3.3.0"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["macros"], default-features = false }
url = "2.3.1"
zip = { version = "0.6.3", features = ["deflate"], default-features = false }
