[package]
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
description = "CLI for Exocore (Distributed applications framework)"
edition = "2021"
keywords = ["networking", "mobile", "webassembly", "storage", "database"]
license = "Apache-2.0"
name = "exo"
repository = "https://github.com/appaquet/exocore"
version = "0.1.21"

[dependencies]
anyhow = "1.0.57"
bytes = "1.1.0"
clap = { version = "3.1.17", features = ["derive", "env"] }
console = "0.15.0"
dialoguer = "0.10.1"
dirs-next = "2.0.0"
exocore-apps-host = {version = "0.1.21", path = "../apps/host"}
exocore-chain = {version = "0.1.21", path = "../chain"}
exocore-core = {version = "0.1.21", path = "../core", features = ["runtime", "logger"]}
exocore-discovery = {version = "0.1.21", path = "../discovery", features = ["server"]}
exocore-protos = {version = "0.1.21", path = "../protos"}
exocore-store = {version = "0.1.21", path = "../store"}
exocore-transport = {version = "0.1.21", path = "../transport", features = ["http-server"]}
futures = "0.3.21"
indicatif = "0.16.2"
log = "0.4.17"
log4rs = "1.1.1"
rand = "0.8"
reqwest = { version = "0.11.10", default-features = false, features = ["rustls-tls"] }
serde = "1.0.137"
serde_derive = "1.0.136"
serde_json = "1.0.81"
tempfile = "3.3.0"
thiserror = "1.0.31"
tokio = { version = "1.18.1", features = ["macros"], default-features = false }
url = "2.2.2"
zip = "0.6.2"
