# Node's keypair and public key
# Use `exo keys generate` to generate node's keys
name: Optional Node Name
public_key: peFdPsQsdqzT2H6cPd3WdU1fGdATDmavh4C17VWWacZTMP
keypair: ae2oiM2PYznyfqEMPraKbpAuA8LWVhPUiUTgdwjvnwbDjnz9W9FAiE9431NtVjfBaX44nPPoNR8Mv6iYcJdqSfp8eZ

# Node's listen addresses
addresses:
  p2p:
    - /ip4/0.0.0.0/tcp/3330
    - /ip4/0.0.0.0/tcp/3341/ws
  http:
    - http://0.0.0.0:8888

# Cells that the node is part of
# Use `exo keys generate` to generate cell's keys
cells:
  # Cell defined inline
  - location:
      Instance:
        public_key: pe2AgPyBmJNztntK9n4vhLuEYN8P2kRfFXnaZFsiXqWacQ
        keypair: ae55Nfv11ppyFVxCDaYovcxTcaTDaSzSFjiVoiC3VwGARfEuaqGcgoJUdVpqfwKQVDN4rvGKUvt4yqQc6w7it7PCpG
        data_directory: /path/to/data
        name: Optional Cell Name
        nodes:
          - node:
              name: Optional Node Name
              public_key: peFdPsQsdqzT2H6cPd3WdU1fGdATDmavh4C17VWWacZTMP
              addresses:
                p2p:
                  - /ip4/127.0.0.1/tcp/3330
                  - /ip4/127.0.0.1/tcp/3341/ws
                http:
                  - http://127.0.0.1:8888

            # Role of the node
            # Chain = 1
            # Store = 2
            roles:
              - 1
              - 2

          - node:
              name: Some Client Node
              public_key: peHdrwp1ZXicF1v7RQRRC4ursqgE1oM9nuVijCmrf74n7E

        apps:
          - location:
              Directory: ./app

  # Cell defined in a directory
  - location:
      Directory: ./cell
