
# Node's keypair and public key
name: Node Name
public_key: peFdPsQsdqzT2H6cPd3WdU1fGdATDmavh4C17VWWacZTMP
keypair: ae2oiM2PYznyfqEMPraKbpAuA8LWVhPUiUTgdwjvnwbDjnz9W9FAiE9431NtVjfBaX44nPPoNR8Mv6iYcJdqSfp8eZ

# Node's listen addresses
listen_addresses:
  - /ip4/0.0.0.0/tcp/3330
  - /ip4/0.0.0.0/tcp/3341/ws

# Cells that the node is part of
cells:
  - public_key: pe2AgPyBmJNztntK9n4vhLuEYN8P2kRfFXnaZFsiXqWacQ
    keypair: ae55Nfv11ppyFVxCDaYovcxTcaTDaSzSFjiVoiC3VwGARfEuaqGcgoJUdVpqfwKQVDN4rvGKUvt4yqQc6w7it7PCpG
    data_directory: target/data
    name: Cell Name
    nodes:
      - node:
          name: Node Name
          public_key: peFdPsQsdqzT2H6cPd3WdU1fGdATDmavh4C17VWWacZTMP
          addresses:
            - /ip4/127.0.0.1/tcp/3330
            - /ip4/127.0.0.1/tcp/3341/ws

        # Role of the node
        # Data = 1
        # Index store = 2
        roles:
          - 1
          - 2
