[package]
name = "exocore-common"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]

[dependencies]
log = "0.4.5"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"

[dev-dependencies]
tempdir = "0.3.7"