[package]
name = "exocore-common"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[features]
tests_utils = ["log4rs"]

[dependencies]
log = "0.4"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
parity-multihash = "0.1.0"
tiny-keccak = "1.4.2"
capnp = { git = "https://github.com/appaquet/capnproto-rust.git", branch = "thread-safe-arena-readlimiter" }
byteorder = "1.2"
owning_ref = "0.4.0"
lazycell = "1.2.1"
failure = "0.1.5"
futures = "0.1.25"
log4rs = { version = "0.8.3", optional = true }

[build-dependencies]
capnpc = "0.9"

[dev-dependencies]
tempdir = "0.3.7"
memmap = "0.7"
log4rs = "0.8.3"
criterion_bencher_compat = "0.2.5"

[[bench]]
name = "capnp_msg"
harness = false