[package]
name = "exocore-common"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"

[features]
default = ["hash_compute"]
hash_compute = ["sha2"]

[dependencies]
log = "0.4"
serde = "1.0.80"
serde_json = "1.0.32"
serde_derive = "1.0.80"
sha2 = {version = "0.8.0", optional = true }
capnp = "0.9"
byteorder = "1.2"

[build-dependencies]
capnpc = "0.9"

[dev-dependencies]
tempdir = "0.3.7"
memmap = "0.7"

