[package]
name = "exocore-chain"
description = "Distributed applications framework"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "web", "framework", "ios", "android", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "MIT"

[features]
default = ["engine", "directory_chain", "memory_pending"]
tests_utils = ["engine", "tempdir", "directory_chain", "memory_pending", "exocore-core/tests_utils", "exocore-transport/tests_utils"]
engine = []
directory_chain = ["memmap", "extindex"]
memory_pending = []

[dependencies]
exocore-core = { path = "../core" }
exocore-transport = { path = "../transport", default-features = false }
log = "0.4"
byteorder = "1.2"
failure = "0.1"
itertools = "0.9"
serde = "1.0"
serde_derive = "1.0"
futures = "0.3"

# For directory chain
memmap = { version = "0.7", optional = true }
extindex = { version = "0.3", optional = true }

# For tests
tempdir = { version = "0.3", optional = true }

[dev-dependencies]
exocore-core = { path = "../core", features = ["tests_utils"] }
exocore-transport = { path = "../transport", features = ["tests_utils"] }
tempdir = "0.3"

[[test]]
name = "engine"
required-features = ["tests_utils"]
