[package]
name = "exocore-chain"
description = "Distributed applications framework"
version = "0.1.0"
authors = ["Andre-Philippe Paquet <appaquet@gmail.com>"]
edition = "2018"
keywords = ["networking", "mobile", "web", "framework", "ios", "android", "webassembly", "storage", "database"]
categories = ["database-implementations", "command-line-interface", "wasm", "web-programming"]
repository = "https://github.com/appaquet/exocore"
license = "Apache-2.0"

[features]
default = ["engine", "directory-chain", "memory-pending"]
tests-utils = ["engine", "tempfile", "directory-chain", "memory-pending", "exocore-core/tests-utils", "exocore-transport/tests-utils"]
engine = []
directory-chain = ["memmap", "extindex"]
memory-pending = []

[dependencies]
exocore-core = { path = "../core" }
exocore-transport = { path = "../transport", default-features = false }
log = "0.4"
byteorder = "1.2"
thiserror = "1.0"
anyhow = "1.0"
itertools = "0.9"
serde = "1.0"
serde_derive = "1.0"
futures = "0.3"

# For directory chain
memmap = { version = "0.7", optional = true }
extindex = { version = "0.3", optional = true }

# For tests
tempfile = { version = "3.1", optional = true }

[dev-dependencies]
exocore-core = { path = "../core", features = ["tests-utils"] }
exocore-transport = { path = "../transport", features = ["tests-utils"] }
tempfile = "3.1"

[[test]]
name = "engine"
required-features = ["tests-utils"]
