name: Release publish

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish'  
        default: true
      ref:
        description: 'Tag'
        default: 'v0.X.X'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        ref: ${{ github.event.inputs.ref }}

    - name: Download release files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -x
        TAG="${{ github.event.inputs.ref }}"

        mkdir assets && cd assets
        hub release download $TAG

        tar -zxf exo.x86_64-unknown-linux-gnu.tar.gz
        mv exo exo-amd64

        tar -zxf exo.armv7-unknown-linux-gnueabihf.tar.gz
        mv exo exo-arm

    - name: Build & publish Docker
      run: |
        TAG="${{ github.event.inputs.ref }}"

        # Allows build in arm for qemu
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker buildx create --use --name exocore-builder 

        echo "${{ github.event.inputs.publish }}"
        if [[ "${{ github.event.inputs.publish }}" == "true" ]]; then 
          echo "WOULD BE PUBLISHING"
        fi

        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

        cd assets/
        docker buildx build \
          --tag appaquet/exocore-cli:$TAG \
          --platform linux/amd64,linux/arm \
          --file ../.github/Dockerfile.buildx \
          .
