name: Release publish

on:
  release:
    types: [created, published]  # TODO: Remove created
  # push:
  #   branches:    
  #     - gha-release

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Build & publish Docker
      run: |
        TAG="${GITHUB_REF##*/}"

        # Allows running arm in qemu
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker buildx create --use --name exocore-builder 

        touch exo-amd64
        touch exo-arm

        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker buildx build \
          --tag appaquet/exocore-cli:$TAG \
          --platform linux/amd64,linux/arm \
          --file .github/Dockerfile.buildx \
          .
