name: Push tester

on: [push]

jobs:
  test_and_check:
    runs-on: ubuntu-latest
    container:
      image: appaquet/exocore-build-cache

    steps:
#      - uses: actions/checkout@v1
#      - name: Install Rust & Tools
#        run: |
#          set -e
#
#          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
#          export PATH=$PATH:$HOME/.cargo/bin:/usr/local/cargo/bin
#          rustc --version && cargo --version
#          rustup component add rustfmt
#          rustup component add clippy

      - name: Check & test
        run: |
          cd $GITHUB_WORKSPACE
          cargo fmt --all -- --check
          cargo check --all
          cargo clean -p exocore-common
          cargo clippy --all -- -D clippy::all

          cargo test --all --all-features

#  coverage:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v1
#      - name: Install Rust & Dependencies
#        run: |
#          set -e
#          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
#          export PATH=$PATH:$HOME/.cargo/bin:/usr/local/cargo/bin
#          rustc --version && cargo --version
#          rustup toolchain install nightly
#
#      - name: Check & test
#        run: |
#          set -e
#          curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -
#          export PATH=$PATH:`pwd`
#          ./utils/coverage.sh codecov_io
#
#          export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
#          bash <(curl -s https://codecov.io/bash)
#
