name: Push tester

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy & check
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  linux_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features

  macos_tests:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features

  windows_tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --all-features

  wasm_build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:19.10 # required for clang with wasm
    steps:
      - uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          set -e

          apt update && DEBIAN_FRONTEND=noninteractive apt install -y clang curl pkg-config libssl-dev openssl

          curl -L https://github.com/rustwasm/wasm-pack/releases/download/v0.9.1/wasm-pack-v0.9.1-x86_64-unknown-linux-musl.tar.gz | tar zxf -
          mv wasm-pack*/wasm-pack .

          curl -sL https://deb.nodesource.com/setup_13.x | bash -
          apt-get install -y nodejs
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
      - name: Build client & example
        run: |
          set -e
          export PATH=$PATH:`pwd`

          cd $GITHUB_WORKSPACE/
          npm ci
          npm run build_dev

          cd $GITHUB_WORKSPACE/examples/web
          npm ci
          npm run build_dev

  ios_build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Install cargo-lipo
        run: |
          set -e
          # actions-rs don't support multiple targets: https://github.com/actions-rs/toolchain/issues/16
          rustup target add aarch64-apple-ios x86_64-apple-ios
          cargo install cargo-lipo
      - name: Force Xcode 11.3
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      - name: Build ios lib
        run: |
          set -e
          export RUST_BACKTRACE=1

          cd $GITHUB_WORKSPACE/clients/ios
          cargo lipo

          cd $GITHUB_WORKSPACE/clients/ios/xcode/exocore-client-ios
          pod install
          xcodebuild -workspace exocore-client-ios.xcworkspace -scheme exocore-client-ios -destination "generic/platform=iOS" CODE_SIGNING_ALLOWED=NO

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-06-21
          profile: minimal
      - name: Test coverage
        run: |
          set -e
          curl -L https://github.com/mozilla/grcov/releases/download/v0.5.9/grcov-linux-x86_64.tar.bz2 | tar jxf -
          export PATH=$PATH:`pwd`
          export RUST_BACKTRACE=1

          export CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
          ./tools/coverage.sh codecov_io
