name: Version builder

on:
  push:
    branches:    
      - 'releases/**'

jobs:
  web_client_build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:19.10 # required for clang with wasm
    steps:
      - uses: actions/checkout@v2.3.1

      - name: Install build dependencies
        run: |
          apt update && DEBIAN_FRONTEND=noninteractive apt install -y clang curl pkg-config libssl-dev openssl

          curl -sL https://deb.nodesource.com/setup_14.x | bash -
          apt-get install -y nodejs protobuf-compiler
          npm install -g yarn

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: |
          curl -L https://github.com/rustwasm/wasm-pack/releases/download/v0.9.1/wasm-pack-v0.9.1-x86_64-unknown-linux-musl.tar.gz | tar zxf -
          mv wasm-pack*/wasm-pack .

      - name: Build client
        run: |
          export PATH=$PATH:`pwd`

          cd $GITHUB_WORKSPACE
          yarn build

          # Remove so that we don't save in artifacts
          rm -rf clients/web/node_modules

      - name: Upload build artifacts
        uses: actions/upload-artifact@2.1.0
        with:
          name: web-artifacts
          path: clients/web


  ios_client_build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install cargo-lipo
        run: |
          brew install swift-protobuf
          rustup target add aarch64-apple-ios x86_64-apple-ios # actions-rs don't support multiple targets: https://github.com/actions-rs/toolchain/issues/16
          cargo install cargo-lipo

      - name: Force Xcode 11.5
        run: sudo xcode-select -switch /Applications/Xcode_11.5.app

      - name: Build client & pod
        run: |
          cd $GITHUB_WORKSPACE/clients/ios
          ./tools/generate.sh
          ./tools/build.sh release

          cd $GITHUB_WORKSPACE/
          pod lib lint --verbose

      - name: Upload build artifacts
        uses: actions/upload-artifact@2.1.0
        with:
          name: ios-artifacts
          path: clients/ios
  

  commit_artifacts:
    runs-on: ubuntu-latest
    needs: [web_client_build, ios_client_build]
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          lfs: true

      - name: Download web artifacts
        uses: actions/download-artifact@v2
        with:
          name: web-artifacts
          path: clients/web

      - name: Download iOS artifacts
        uses: actions/download-artifact@v2
        with:
          name: ios-artifacts
          path: clients/ios

      - name: List artifacts
        run: |
          set -e
          ls -R clients/ios
          ls -R clients/web

      - name: Commit assets 
        uses: EndBug/add-and-commit@v4
        with:
          add: 'web/wasm web/tsc web/protos ios/lib ios/swift/protos'
          author_name: Exocore bot
          cwd: 'clients'
          force: true
          message: 'Build assets'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
